#Dockerfile used for auto build https://hub.docker.com/r/robertjensen/cas
FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install curl -y
RUN apt-get install python -y
RUN apt-get install sshpass -y
RUN apt-get install wget -y
RUN apt-get install packer -y
